/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Duration = IDL.Variant({
  'thirtyMin' : IDL.Null,
  'fifteenMin' : IDL.Null,
  'fiveMin' : IDL.Null,
  'fortyFiveMin' : IDL.Null,
});
export const EnergyLevel = IDL.Variant({
  'morning' : IDL.Null,
  'evening' : IDL.Null,
  'afternoon' : IDL.Null,
});
export const Priority = IDL.Variant({
  'low' : IDL.Null,
  'high' : IDL.Null,
  'medium' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'timezone' : IDL.Text,
  'energyPreference' : EnergyLevel,
  'name' : IDL.Text,
  'accentColor' : IDL.Text,
});
export const TaskStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'archived' : IDL.Null,
});
export const Task = IDL.Record({
  'id' : IDL.Nat,
  'status' : TaskStatus,
  'title' : IDL.Text,
  'duration' : Duration,
  'associatedProjectId' : IDL.Opt(IDL.Nat),
  'createdBy' : IDL.Principal,
  'energyRequirement' : EnergyLevel,
  'dueDate' : IDL.Int,
  'priority' : Priority,
  'editCount' : IDL.Nat,
});
export const MindDumpItem = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'createdBy' : IDL.Principal,
  'timestamp' : IDL.Int,
});
export const Project = IDL.Record({
  'id' : IDL.Nat,
  'tasks' : IDL.Vec(IDL.Nat),
  'name' : IDL.Text,
  'createdBy' : IDL.Principal,
  'energyRequirement' : EnergyLevel,
  'estimatedDuration' : Duration,
});
export const WeeklyReview = IDL.Record({
  'id' : IDL.Nat,
  'failures' : IDL.Text,
  'avoidance' : IDL.Text,
  'createdBy' : IDL.Principal,
  'wins' : IDL.Text,
  'timestamp' : IDL.Int,
  'priorities' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addMindDump' : IDL.Func([IDL.Text], [], []),
  'addProject' : IDL.Func([IDL.Text, Duration, EnergyLevel], [], []),
  'addTask' : IDL.Func([IDL.Text, Priority, Duration, EnergyLevel], [], []),
  'addWeeklyReview' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clarifyMindDump' : IDL.Func(
      [IDL.Nat, IDL.Bool, IDL.Text, Duration, EnergyLevel, IDL.Opt(IDL.Nat)],
      [],
      [],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCurrentDailyTasks' : IDL.Func([], [IDL.Opt(IDL.Vec(Task))], ['query']),
  'getUserMindDumps' : IDL.Func([], [IDL.Vec(MindDumpItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
  'getUserTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getUserWeeklyReviews' : IDL.Func([], [IDL.Vec(WeeklyReview)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markTaskDone' : IDL.Func([IDL.Nat], [], []),
  'resetWeeklyTasks' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Duration = IDL.Variant({
    'thirtyMin' : IDL.Null,
    'fifteenMin' : IDL.Null,
    'fiveMin' : IDL.Null,
    'fortyFiveMin' : IDL.Null,
  });
  const EnergyLevel = IDL.Variant({
    'morning' : IDL.Null,
    'evening' : IDL.Null,
    'afternoon' : IDL.Null,
  });
  const Priority = IDL.Variant({
    'low' : IDL.Null,
    'high' : IDL.Null,
    'medium' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'timezone' : IDL.Text,
    'energyPreference' : EnergyLevel,
    'name' : IDL.Text,
    'accentColor' : IDL.Text,
  });
  const TaskStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'archived' : IDL.Null,
  });
  const Task = IDL.Record({
    'id' : IDL.Nat,
    'status' : TaskStatus,
    'title' : IDL.Text,
    'duration' : Duration,
    'associatedProjectId' : IDL.Opt(IDL.Nat),
    'createdBy' : IDL.Principal,
    'energyRequirement' : EnergyLevel,
    'dueDate' : IDL.Int,
    'priority' : Priority,
    'editCount' : IDL.Nat,
  });
  const MindDumpItem = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'createdBy' : IDL.Principal,
    'timestamp' : IDL.Int,
  });
  const Project = IDL.Record({
    'id' : IDL.Nat,
    'tasks' : IDL.Vec(IDL.Nat),
    'name' : IDL.Text,
    'createdBy' : IDL.Principal,
    'energyRequirement' : EnergyLevel,
    'estimatedDuration' : Duration,
  });
  const WeeklyReview = IDL.Record({
    'id' : IDL.Nat,
    'failures' : IDL.Text,
    'avoidance' : IDL.Text,
    'createdBy' : IDL.Principal,
    'wins' : IDL.Text,
    'timestamp' : IDL.Int,
    'priorities' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addMindDump' : IDL.Func([IDL.Text], [], []),
    'addProject' : IDL.Func([IDL.Text, Duration, EnergyLevel], [], []),
    'addTask' : IDL.Func([IDL.Text, Priority, Duration, EnergyLevel], [], []),
    'addWeeklyReview' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clarifyMindDump' : IDL.Func(
        [IDL.Nat, IDL.Bool, IDL.Text, Duration, EnergyLevel, IDL.Opt(IDL.Nat)],
        [],
        [],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCurrentDailyTasks' : IDL.Func([], [IDL.Opt(IDL.Vec(Task))], ['query']),
    'getUserMindDumps' : IDL.Func([], [IDL.Vec(MindDumpItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProjects' : IDL.Func([], [IDL.Vec(Project)], ['query']),
    'getUserTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getUserWeeklyReviews' : IDL.Func([], [IDL.Vec(WeeklyReview)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markTaskDone' : IDL.Func([IDL.Nat], [], []),
    'resetWeeklyTasks' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };