/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Duration = { 'thirtyMin' : null } |
  { 'fifteenMin' : null } |
  { 'fiveMin' : null } |
  { 'fortyFiveMin' : null };
export type EnergyLevel = { 'morning' : null } |
  { 'evening' : null } |
  { 'afternoon' : null };
export interface MindDumpItem {
  'id' : bigint,
  'content' : string,
  'createdBy' : Principal,
  'timestamp' : bigint,
}
export type Priority = { 'low' : null } |
  { 'high' : null } |
  { 'medium' : null };
export interface Project {
  'id' : bigint,
  'tasks' : Array<bigint>,
  'name' : string,
  'createdBy' : Principal,
  'energyRequirement' : EnergyLevel,
  'estimatedDuration' : Duration,
}
export interface Task {
  'id' : bigint,
  'status' : TaskStatus,
  'title' : string,
  'duration' : Duration,
  'associatedProjectId' : [] | [bigint],
  'createdBy' : Principal,
  'energyRequirement' : EnergyLevel,
  'dueDate' : bigint,
  'priority' : Priority,
  'editCount' : bigint,
}
export type TaskStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'archived' : null };
export interface UserProfile {
  'timezone' : string,
  'energyPreference' : EnergyLevel,
  'name' : string,
  'accentColor' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WeeklyReview {
  'id' : bigint,
  'failures' : string,
  'avoidance' : string,
  'createdBy' : Principal,
  'wins' : string,
  'timestamp' : bigint,
  'priorities' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addMindDump' : ActorMethod<[string], undefined>,
  'addProject' : ActorMethod<[string, Duration, EnergyLevel], undefined>,
  'addTask' : ActorMethod<[string, Priority, Duration, EnergyLevel], undefined>,
  'addWeeklyReview' : ActorMethod<[string, string, string, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clarifyMindDump' : ActorMethod<
    [bigint, boolean, string, Duration, EnergyLevel, [] | [bigint]],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCurrentDailyTasks' : ActorMethod<[], [] | [Array<Task>]>,
  'getUserMindDumps' : ActorMethod<[], Array<MindDumpItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUserProjects' : ActorMethod<[], Array<Project>>,
  'getUserTasks' : ActorMethod<[], Array<Task>>,
  'getUserWeeklyReviews' : ActorMethod<[], Array<WeeklyReview>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markTaskDone' : ActorMethod<[bigint], undefined>,
  'resetWeeklyTasks' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];