/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Task {
    id: bigint;
    status: TaskStatus;
    title: string;
    duration: Duration;
    associatedProjectId?: bigint;
    createdBy: Principal;
    energyRequirement: EnergyLevel;
    dueDate: bigint;
    priority: Priority;
    editCount: bigint;
}
export interface MindDumpItem {
    id: bigint;
    content: string;
    createdBy: Principal;
    timestamp: bigint;
}
export interface Project {
    id: bigint;
    tasks: Array<bigint>;
    name: string;
    createdBy: Principal;
    energyRequirement: EnergyLevel;
    estimatedDuration: Duration;
}
export interface WeeklyReview {
    id: bigint;
    failures: string;
    avoidance: string;
    createdBy: Principal;
    wins: string;
    timestamp: bigint;
    priorities: string;
}
export interface UserProfile {
    timezone: string;
    energyPreference: EnergyLevel;
    name: string;
    accentColor: string;
}
export enum Duration {
    thirtyMin = "thirtyMin",
    fifteenMin = "fifteenMin",
    fiveMin = "fiveMin",
    fortyFiveMin = "fortyFiveMin"
}
export enum EnergyLevel {
    morning = "morning",
    evening = "evening",
    afternoon = "afternoon"
}
export enum Priority {
    low = "low",
    high = "high",
    medium = "medium"
}
export enum TaskStatus {
    pending = "pending",
    completed = "completed",
    archived = "archived"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addMindDump(content: string): Promise<void>;
    addProject(name: string, estimatedDuration: Duration, energyRequirement: EnergyLevel): Promise<void>;
    addTask(title: string, priority: Priority, duration: Duration, energyRequirement: EnergyLevel): Promise<void>;
    addWeeklyReview(wins: string, failures: string, avoidance: string, priorities: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clarifyMindDump(mindDumpId: bigint, isActionable: boolean, nextStep: string, duration: Duration, energyRequirement: EnergyLevel, projectId: bigint | null): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCurrentDailyTasks(): Promise<Array<Task> | null>;
    getUserMindDumps(): Promise<Array<MindDumpItem>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getUserProjects(): Promise<Array<Project>>;
    getUserTasks(): Promise<Array<Task>>;
    getUserWeeklyReviews(): Promise<Array<WeeklyReview>>;
    isCallerAdmin(): Promise<boolean>;
    markTaskDone(taskId: bigint): Promise<void>;
    resetWeeklyTasks(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
}
import type { Duration as _Duration, EnergyLevel as _EnergyLevel, Priority as _Priority, Project as _Project, Task as _Task, TaskStatus as _TaskStatus, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addMindDump(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMindDump(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMindDump(arg0);
            return result;
        }
    }
    async addProject(arg0: string, arg1: Duration, arg2: EnergyLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addProject(arg0, to_candid_Duration_n1(this._uploadFile, this._downloadFile, arg1), to_candid_EnergyLevel_n3(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProject(arg0, to_candid_Duration_n1(this._uploadFile, this._downloadFile, arg1), to_candid_EnergyLevel_n3(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async addTask(arg0: string, arg1: Priority, arg2: Duration, arg3: EnergyLevel): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addTask(arg0, to_candid_Priority_n5(this._uploadFile, this._downloadFile, arg1), to_candid_Duration_n1(this._uploadFile, this._downloadFile, arg2), to_candid_EnergyLevel_n3(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addTask(arg0, to_candid_Priority_n5(this._uploadFile, this._downloadFile, arg1), to_candid_Duration_n1(this._uploadFile, this._downloadFile, arg2), to_candid_EnergyLevel_n3(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async addWeeklyReview(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addWeeklyReview(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addWeeklyReview(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n7(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clarifyMindDump(arg0: bigint, arg1: boolean, arg2: string, arg3: Duration, arg4: EnergyLevel, arg5: bigint | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clarifyMindDump(arg0, arg1, arg2, to_candid_Duration_n1(this._uploadFile, this._downloadFile, arg3), to_candid_EnergyLevel_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clarifyMindDump(arg0, arg1, arg2, to_candid_Duration_n1(this._uploadFile, this._downloadFile, arg3), to_candid_EnergyLevel_n3(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n9(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCurrentDailyTasks(): Promise<Array<Task> | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCurrentDailyTasks();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCurrentDailyTasks();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserMindDumps(): Promise<Array<MindDumpItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMindDumps();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMindDumps();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProjects(): Promise<Array<Project>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProjects();
                return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProjects();
            return from_candid_vec_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserTasks();
                return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserTasks();
            return from_candid_vec_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserWeeklyReviews(): Promise<Array<WeeklyReview>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserWeeklyReviews();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserWeeklyReviews();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markTaskDone(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markTaskDone(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markTaskDone(arg0);
            return result;
        }
    }
    async resetWeeklyTasks(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetWeeklyTasks();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetWeeklyTasks();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Duration_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Duration): Duration {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_EnergyLevel_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EnergyLevel): EnergyLevel {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Priority_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Priority): Priority {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Project_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Project): Project {
    return from_candid_record_n30(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Array<_Task>]): Array<Task> | null {
    return value.length === 0 ? null : from_candid_vec_n18(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timezone: string;
    energyPreference: _EnergyLevel;
    name: string;
    accentColor: string;
}): {
    timezone: string;
    energyPreference: EnergyLevel;
    name: string;
    accentColor: string;
} {
    return {
        timezone: value.timezone,
        energyPreference: from_candid_EnergyLevel_n13(_uploadFile, _downloadFile, value.energyPreference),
        name: value.name,
        accentColor: value.accentColor
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _TaskStatus;
    title: string;
    duration: _Duration;
    associatedProjectId: [] | [bigint];
    createdBy: Principal;
    energyRequirement: _EnergyLevel;
    dueDate: bigint;
    priority: _Priority;
    editCount: bigint;
}): {
    id: bigint;
    status: TaskStatus;
    title: string;
    duration: Duration;
    associatedProjectId?: bigint;
    createdBy: Principal;
    energyRequirement: EnergyLevel;
    dueDate: bigint;
    priority: Priority;
    editCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_TaskStatus_n21(_uploadFile, _downloadFile, value.status),
        title: value.title,
        duration: from_candid_Duration_n23(_uploadFile, _downloadFile, value.duration),
        associatedProjectId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.associatedProjectId)),
        createdBy: value.createdBy,
        energyRequirement: from_candid_EnergyLevel_n13(_uploadFile, _downloadFile, value.energyRequirement),
        dueDate: value.dueDate,
        priority: from_candid_Priority_n26(_uploadFile, _downloadFile, value.priority),
        editCount: value.editCount
    };
}
function from_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    tasks: Array<bigint>;
    name: string;
    createdBy: Principal;
    energyRequirement: _EnergyLevel;
    estimatedDuration: _Duration;
}): {
    id: bigint;
    tasks: Array<bigint>;
    name: string;
    createdBy: Principal;
    energyRequirement: EnergyLevel;
    estimatedDuration: Duration;
} {
    return {
        id: value.id,
        tasks: value.tasks,
        name: value.name,
        createdBy: value.createdBy,
        energyRequirement: from_candid_EnergyLevel_n13(_uploadFile, _downloadFile, value.energyRequirement),
        estimatedDuration: from_candid_Duration_n23(_uploadFile, _downloadFile, value.estimatedDuration)
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    morning: null;
} | {
    evening: null;
} | {
    afternoon: null;
}): EnergyLevel {
    return "morning" in value ? EnergyLevel.morning : "evening" in value ? EnergyLevel.evening : "afternoon" in value ? EnergyLevel.afternoon : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    archived: null;
}): TaskStatus {
    return "pending" in value ? TaskStatus.pending : "completed" in value ? TaskStatus.completed : "archived" in value ? TaskStatus.archived : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    thirtyMin: null;
} | {
    fifteenMin: null;
} | {
    fiveMin: null;
} | {
    fortyFiveMin: null;
}): Duration {
    return "thirtyMin" in value ? Duration.thirtyMin : "fifteenMin" in value ? Duration.fifteenMin : "fiveMin" in value ? Duration.fiveMin : "fortyFiveMin" in value ? Duration.fortyFiveMin : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    low: null;
} | {
    high: null;
} | {
    medium: null;
}): Priority {
    return "low" in value ? Priority.low : "high" in value ? Priority.high : "medium" in value ? Priority.medium : value;
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Project>): Array<Project> {
    return value.map((x)=>from_candid_Project_n29(_uploadFile, _downloadFile, x));
}
function to_candid_Duration_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Duration): _Duration {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_EnergyLevel_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnergyLevel): _EnergyLevel {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Priority_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): _Priority {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n32(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    timezone: string;
    energyPreference: EnergyLevel;
    name: string;
    accentColor: string;
}): {
    timezone: string;
    energyPreference: _EnergyLevel;
    name: string;
    accentColor: string;
} {
    return {
        timezone: value.timezone,
        energyPreference: to_candid_EnergyLevel_n3(_uploadFile, _downloadFile, value.energyPreference),
        name: value.name,
        accentColor: value.accentColor
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Duration): {
    thirtyMin: null;
} | {
    fifteenMin: null;
} | {
    fiveMin: null;
} | {
    fortyFiveMin: null;
} {
    return value == Duration.thirtyMin ? {
        thirtyMin: null
    } : value == Duration.fifteenMin ? {
        fifteenMin: null
    } : value == Duration.fiveMin ? {
        fiveMin: null
    } : value == Duration.fortyFiveMin ? {
        fortyFiveMin: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EnergyLevel): {
    morning: null;
} | {
    evening: null;
} | {
    afternoon: null;
} {
    return value == EnergyLevel.morning ? {
        morning: null
    } : value == EnergyLevel.evening ? {
        evening: null
    } : value == EnergyLevel.afternoon ? {
        afternoon: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Priority): {
    low: null;
} | {
    high: null;
} | {
    medium: null;
} {
    return value == Priority.low ? {
        low: null
    } : value == Priority.high ? {
        high: null
    } : value == Priority.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
